autoload:

  plugins_actions:
    path: %SF_PLUGINS_DIR%/*/modules/*/actions

  actions:
    path: %SF_APP_DIR%/modules/*/actions

  net_gearman:
    path: %SF_ROOT_DIR%/vendor/net_gearman/Net/Gearman
    recursive: on
